default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      # language_version: python3.10
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint
#       language: system
#       types: [python]
#       args: [
#         "-rn", # Only display messages
#         "-sn", # Don't display the score
#         "--recursive=y"
#       ]
# - repo: local
#   hooks:
#     - id: pytest-check
#       name: pytest-check
#       stages: [commit]
#       types: [python]
#       entry: pytest # entry: poetry run pytest
#       language: system
#       pass_filenames: false
#       always_run: true
#       args: [
#         "-k not summarizer and ping"
#       ]
